spring:
  application:
    name: core-api
  datasource:
    url: jdbc:postgresql://postgres:5432/vyomin_db
    username: ${POSTGRES_USER:vyomin_admin}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379
    neo4j:
      database: ${NEO4J_AURA_DATABASE}
  neo4j:
    uri: ${NEO4J_AURA_URI}
    authentication:
      username: ${NEO4J_AURA_USERNAME}
      password: ${NEO4J_AURA_PASSWORD}
gdelt:
  manifest:
    url: ${GDELT_MANIFEST_URL:http://data.gdeltproject.org/gdeltv2/lastupdate.txt}
  cameo:
    country:
      url: ${GDELT_CAMEO_COUNTRY_URL:http://data.gdeltproject.org/documentation/CAMEO.country.txt}
    type:
      url: ${GDELT_CAMEO_TYPE_URL:http://data.gdeltproject.org/documentation/CAMEO.type.txt}
    event:
      url: ${GDELT_CAMEO_EVENT_URL:http://data.gdeltproject.org/documentation/CAMEO.eventcodes.txt}
  conflict:
    retention-days: ${GDELT_CONFLICT_RETENTION_DAYS:180}
api:
  finnhub:
    key: ${FINNHUB_API_KEY:}
  opensanctions:
    key: ${OPENSANCTIONS_API_KEY}
  opennetwork:
    clientId: ${Open_Network_clientId}
    clientSecret: ${Open_Network_clientSecret}
    tokenUrl: ${Open_Network_token_url}
    dataUrl: ${Open_Network_data_url}
app:
  admin:
    email: ${DEFAULT_ADMIN_EMAIL}
    password: ${DEFAULT_ADMIN_PASSWORD}
  jwt:
    secret: ${APP_JWT_SECRET:CHANGE_ME_IN_ENVIRONMENT}
google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:}
